# pylint: disable=line-too-long, redefined-builtin, too-many-arguments, too-many-locals, unused-argument, unused-import, too-many-ancestors  # noqa: E501
"""
Autogenerated file
DO NOT EDIT.
"""
import typing

from dash_component_system import (
    DashComponent, UNDEFINED, Undefined, ComponentProp
)


class Checklist(DashComponent):
    """
    Checklist is a component that encapsulates several checkboxes. The values
    and labels of the checklist is specified in the `options` property and the
    checked items are specified with the `values` property. Each checkbox is
    rendered as an input with a surrounding label.
    """

    _namespace = 'dash_core_components'
    _typename = 'Checklist'
    available_wildcard_properties = [

    ]
    id = ComponentProp('id', UNDEFINED, False)
    options = ComponentProp('options', UNDEFINED, False)
    values = ComponentProp('values', UNDEFINED, False)
    className = ComponentProp('className', UNDEFINED, False)
    style = ComponentProp('style', UNDEFINED, False)
    inputStyle = ComponentProp('inputStyle', UNDEFINED, False)
    inputClassName = ComponentProp('inputClassName', '', False)
    labelStyle = ComponentProp('labelStyle', UNDEFINED, False)
    labelClassName = ComponentProp('labelClassName', '', False)
    loading_state = ComponentProp('loading_state', UNDEFINED, False)

    def __init__(
            self,
            id=UNDEFINED,
            options=UNDEFINED,
            values=UNDEFINED,
            className=UNDEFINED,
            style=UNDEFINED,
            inputStyle=UNDEFINED,
            inputClassName='',
            labelStyle=UNDEFINED,
            labelClassName='',
            loading_state=UNDEFINED,
    ):
        # type: (typing.Union[str, Undefined], typing.Union[typing.List[typing.Dict[str, typing.Union[str, bool]]], Undefined], typing.Union[typing.List[str], Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict[str, typing.Union[bool, str]], Undefined]) -> None # noqa: E501
        """
        :param id:
        :param options: An array of options(default=[])
        :param values: The currently selected value
        :param className: The class of the container (div)
        :param style: The style of the container (div)
        :param inputStyle: The style of the <input> checkbox
            element(default={})
        :param inputClassName: The class of the <input> checkbox
            element(default='')
        :param labelStyle: The style of the <label> that wraps the checkbox
            input  and the option's label(default={})
        :param labelClassName: The class of the <label> that wraps the
            checkbox input  and the option's
            label(default='')
        :param loading_state: Object that holds the loading state object
            coming from dash-renderer
        """
        DashComponent.__init__(self, locals())
