"""
Autogenerated file
DO NOT EDIT.
CONTENT WILL BE OVERWRITTEN!

WARNING: Do not import this file directly!
"""
import typing

from dash_component_system import (
    DashComponent, UNDEFINED, Undefined, ComponentProp
)


class ConfirmDialog(DashComponent):
    """
    ConfirmDialog is used to display the browser's native "confirm" modal,
    with an optional message and two buttons ("OK" and "Cancel"). This
    ConfirmDialog can be used in conjunction with buttons when the user is
    performing an action that should require an extra step of verification.
    """
    _namespace = 'dash_core_components'
    _typename = 'ConfirmDialog'
    available_wildcard_properties = [

    ]
    id = ComponentProp('id', UNDEFINED, False)
    message = ComponentProp('message', UNDEFINED, False)
    submit_n_clicks = ComponentProp('submit_n_clicks', 0, False)
    submit_n_clicks_timestamp = ComponentProp('submit_n_clicks_timestamp', -1, False)
    cancel_n_clicks = ComponentProp('cancel_n_clicks', 0, False)
    cancel_n_clicks_timestamp = ComponentProp('cancel_n_clicks_timestamp', -1, False)
    displayed = ComponentProp('displayed', UNDEFINED, False)
    key = ComponentProp('key', UNDEFINED, False)

    def __init__(
        self,
        id=UNDEFINED,
        message=UNDEFINED,
        submit_n_clicks=0,
        submit_n_clicks_timestamp=-1,
        cancel_n_clicks=0,
        cancel_n_clicks_timestamp=-1,
        displayed=UNDEFINED,
        key=UNDEFINED,
        **kwargs
    ):
        # type: (typing.Union[str, Undefined], typing.Union[str, Undefined], typing.Union[typing.Union[float, int], Undefined], typing.Union[typing.Union[float, int], Undefined], typing.Union[typing.Union[float, int], Undefined], typing.Union[typing.Union[float, int], Undefined], typing.Union[bool, Undefined], typing.Union[str, Undefined], typing.Any) -> None # noqa: E501
        """
        :param id:
        :param message: Message to show in the popup.
        :param submit_n_clicks: Number of times the submit button was
            clicked
        :param submit_n_clicks_timestamp: Last time the submit button was
            clicked.
        :param cancel_n_clicks: Number of times the popup was canceled.
        :param cancel_n_clicks_timestamp: Last time the cancel button was
            clicked.
        :param displayed: Set to true to send the ConfirmDialog.
        :param key:
        """
        kws = {
            k: v for k, v in locals().items() if k not in ('self', 'kwargs')
        }
        kws.update(kwargs)
        DashComponent.__init__(self, **kws)
