"""
Autogenerated file
DO NOT EDIT.
CONTENT WILL BE OVERWRITTEN!

WARNING: Do not import this file directly!
"""
import typing

from dash_component_system import (
    DashComponent, UNDEFINED, Undefined, ComponentProp
)


class Link(DashComponent):
    """
    
    """
    _namespace = 'dash_core_components'
    _typename = 'Link'
    available_wildcard_properties = [

    ]
    href = ComponentProp('href', UNDEFINED, False)
    refresh = ComponentProp('refresh', False, False)
    className = ComponentProp('className', UNDEFINED, False)
    style = ComponentProp('style', UNDEFINED, False)
    id = ComponentProp('id', UNDEFINED, False)
    children = ComponentProp('children', UNDEFINED, False)
    loading_state = ComponentProp('loading_state', UNDEFINED, False)

    def __init__(
        self,
        children=UNDEFINED,
        href=UNDEFINED,
        refresh=False,
        className=UNDEFINED,
        style=UNDEFINED,
        id=UNDEFINED,
        loading_state=UNDEFINED,
        **kwargs
    ):
        # type: (typing.Union[typing.Union[str, int, float, DashComponent,typing.List[typing.Union[str, int, float, DashComponent]]], Undefined], typing.Union[str, Undefined], typing.Union[bool, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict[str, typing.Union[bool, str]], Undefined], typing.Any) -> None # noqa: E501
        """
        :param href:
        :param refresh:
        :param className:
        :param style:
        :param id:
        :param children:
        :param loading_state: Object that holds the loading state object
            coming from dash-renderer
        """
        kws = {
            k: v for k, v in locals().items() if k not in ('self', 'kwargs')
        }
        kws.update(kwargs)
        DashComponent.__init__(self, **kws)
