"""
Autogenerated file
DO NOT EDIT.
CONTENT WILL BE OVERWRITTEN!

WARNING: Do not import this file directly!
"""
import typing

from dash_component_system import (
    DashComponent, UNDEFINED, Undefined, ComponentProp
)


class Markdown(DashComponent):
    """
    A component that renders Markdown text as specified by the CommonMark
    spec.
    """
    _namespace = 'dash_core_components'
    _typename = 'Markdown'
    id = ComponentProp('id', UNDEFINED, False)
    className = ComponentProp('className', UNDEFINED, False)
    containerProps = ComponentProp('containerProps', UNDEFINED, False)
    dangerously_allow_html = ComponentProp('dangerously_allow_html', False, False)
    children = ComponentProp('children', UNDEFINED, False)
    loading_state = ComponentProp('loading_state', UNDEFINED, False)

    def __init__(
        self,
        children=UNDEFINED,
        id=UNDEFINED,
        className=UNDEFINED,
        containerProps=UNDEFINED,
        dangerously_allow_html=False,
        loading_state=UNDEFINED,
        **kwargs
    ):
        # type: (typing.Union[typing.Union[str,typing.List[str]], Undefined], typing.Union[str, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[bool, Undefined], typing.Union[typing.Dict[str, typing.Union[bool, str]], Undefined], typing.Any) -> None # noqa: E501
        """
        :param id:
        :param className: Class name of the container element
        :param containerProps: An object containing custom element props to
            put on the container element such as id or
            style
        :param dangerously_allow_html: A boolean to control raw HTML
            escaping. Setting HTML from code is
            risky because it's easy to
            inadvertently expose your users to a
            cross-site scripting (XSS) (https://
            en.wikipedia.org/wiki/Cross-
            site_scripting) attack.
        :param children: A markdown string (or array of strings) that
            adhreres to the CommonMark spec
        :param loading_state: Object that holds the loading state object
            coming from dash-renderer
        """
        kws = {k: v for k, v in locals().items() if k != 'self'}
        DashComponent.__init__(self, **kws)
