"""
Autogenerated file
DO NOT EDIT.
CONTENT WILL BE OVERWRITTEN!

WARNING: Do not import this file directly!
"""
import typing

from dash_component_system import (
    DashComponent, UNDEFINED, Undefined, ComponentProp
)


class RadioItems(DashComponent):
    """
    RadioItems is a component that encapsulates several radio item inputs. The
    values and labels of the RadioItems is specified in the `options` property
    and the seleced item is specified with the `value` property. Each radio
    item is rendered as an input with a surrounding label.
    """
    _namespace = 'dash_core_components'
    _typename = 'RadioItems'
    id = ComponentProp('id', UNDEFINED, False)
    options = ComponentProp('options', "[]", False)
    value = ComponentProp('value', UNDEFINED, False)
    style = ComponentProp('style', UNDEFINED, False)
    className = ComponentProp('className', UNDEFINED, False)
    inputStyle = ComponentProp('inputStyle', "{}", False)
    inputClassName = ComponentProp('inputClassName', '', False)
    labelStyle = ComponentProp('labelStyle', "{}", False)
    labelClassName = ComponentProp('labelClassName', '', False)
    loading_state = ComponentProp('loading_state', UNDEFINED, False)

    def __init__(
        self,
        id=UNDEFINED,
        options="[]",
        value=UNDEFINED,
        style=UNDEFINED,
        className=UNDEFINED,
        inputStyle="{}",
        inputClassName='',
        labelStyle="{}",
        labelClassName='',
        loading_state=UNDEFINED,
        **kwargs
    ):
        # type: (typing.Union[str, Undefined], typing.Union[typing.List[typing.Dict[str, typing.Union[str, bool]]], Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict[str, typing.Union[bool, str]], Undefined], typing.Any) -> None # noqa: E501
        """
        :param id:
        :param options: An array of options
        :param value: The currently selected value
        :param style: The style of the container (div)
        :param className: The class of the container (div)
        :param inputStyle: The style of the <input> radio element
        :param inputClassName: The class of the <input> radio element
        :param labelStyle: The style of the <label> that wraps the radio
            input  and the option's label
        :param labelClassName: The class of the <label> that wraps the
            radio input  and the option's label
        :param loading_state: Object that holds the loading state object
            coming from dash-renderer
        """
        kws = {k: v for k, v in locals().items() if k != 'self'}
        DashComponent.__init__(self, **kws)
