"""
Autogenerated file
DO NOT EDIT.
"""
import typing

from dash_component_system import (
    DashComponent, UNDEFINED, Undefined, ComponentProp
)


class Tab(DashComponent):
    """
    
    """
    _namespace = 'dash_core_components'
    _typename = 'Tab'
    available_wildcard_properties = [

    ]
    id = ComponentProp('id', UNDEFINED, False)
    label = ComponentProp('label', UNDEFINED, False)
    children = ComponentProp('children', UNDEFINED, False)
    value = ComponentProp('value', UNDEFINED, False)
    disabled = ComponentProp('disabled', False, False)
    disabled_style = ComponentProp('disabled_style', "{\n    color: '#d6d6d6',\n}", False)
    disabled_className = ComponentProp('disabled_className', UNDEFINED, False)
    className = ComponentProp('className', UNDEFINED, False)
    selected_className = ComponentProp('selected_className', UNDEFINED, False)
    style = ComponentProp('style', UNDEFINED, False)
    selected_style = ComponentProp('selected_style', UNDEFINED, False)
    loading_state = ComponentProp('loading_state', UNDEFINED, False)

    def __init__(
        self,
        children=UNDEFINED,
        id=UNDEFINED,
        label=UNDEFINED,
        value=UNDEFINED,
        disabled=False,
        disabled_style="{\n    color: '#d6d6d6',\n}",
        disabled_className=UNDEFINED,
        className=UNDEFINED,
        selected_className=UNDEFINED,
        style=UNDEFINED,
        selected_style=UNDEFINED,
        loading_state=UNDEFINED,
    ):
        # type: (typing.Union[typing.Union[str, int, float, DashComponent,typing.List[typing.Union[str, int, float, DashComponent]]], Undefined], typing.Union[str, Undefined], typing.Union[str, Undefined], typing.Union[str, Undefined], typing.Union[bool, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[str, Undefined], typing.Union[str, Undefined], typing.Union[str, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[typing.Dict, Undefined], typing.Union[typing.Dict[str, typing.Union[bool, str]], Undefined]) -> None # noqa: E501
        """
        :param id: The ID of this component, used to identify dash
            components in callbacks. The ID needs to be unique
            across all of the components in an app.
        :param label: The tab's label
        :param children: The content of the tab - will only be displayed if
            this tab is selected
        :param value: Value for determining which Tab is currently selected
        :param disabled: Determines if tab is disabled or not - defaults to
            false
        :param disabled_style: Overrides the default (inline) styles when
            disabled
        :param disabled_className: Appends a class to the Tab component
            when it is disabled.
        :param className: Appends a class to the Tab component.
        :param selected_className: Appends a class to the Tab component
            when it is selected.
        :param style: Overrides the default (inline) styles for the Tab
            component.
        :param selected_style: Overrides the default (inline) styles for
            the Tab component when it is selected.
        :param loading_state: Object that holds the loading state object
            coming from dash-renderer
        """
        DashComponent.__init__(self, locals())
