.dashCoreComponents_js_metadata <- function() {
deps_metadata <- list(`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~datepicker.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~dropdown.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~graph.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~markdown.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~upload.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~datepicker.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~dropdown.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~graph.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~markdown.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~upload.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'highlight.pack.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_core_components.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_core_components.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~graph.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~graph.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.51.2", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'plotly-1.51.2.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~plotlyjs.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"),
`dash_core_components` = structure(list(name = "dash_core_components",
version = "1.6.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~plotlyjs.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashCoreComponents",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
